# Generated by Django 3.1.2 on 2021-04-30 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='offenders_images/')),
                ('date_of_birth', models.DateField()),
                ('state_of_origin', models.CharField(max_length=40)),
                ('nationality', models.CharField(default='Nigeria', max_length=40)),
                ('BVN', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10, null=True)),
                ('marital', models.CharField(blank=True, choices=[('single', 'single'), ('married', 'married'), ('other', 'other')], max_length=10, null=True, verbose_name='Marital Status')),
                ('eye_colour', models.CharField(blank=True, max_length=20, null=True)),
                ('hair_colour', models.CharField(blank=True, max_length=20, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('extra_note', models.TextField(blank=True, max_length=300, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SentencingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('offence', models.CharField(max_length=70)),
                ('entity', models.CharField(max_length=75)),
                ('charge', models.CharField(max_length=70)),
                ('term', models.CharField(blank=True, max_length=20, null=True)),
                ('criminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='crime_records.crimerecord')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
