# Generated by Django 3.1.4 on 2020-12-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='offenders_images/')),
                ('date_of_birth', models.DateField()),
                ('state_of_origin', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=40)),
                ('BVN', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('extra_note', models.CharField(max_length=300)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
